stages:
  - build_and_push
  - deploy

variables:
  DOCKER_REGISTRY: <DOCKER_REGISTRY>
  DOCKER_REGISTRY_USER : <DOCKER_REGISTRY_USER>
  DOCKER_REGISTRY_PASSWORD: <DOCKER_REGISTRY_PASSWORD>

build-and-push:
  stage: build_and_push
  script:
    - cd ./app && docker build --no-cache -t ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_BRANCH}.${CI_PIPELINE_ID} -t ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_BRANCH}-latest .
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
    - docker push $DOCKER_REGISTRY/${CI_PROJECT_NAME}:${CI_COMMIT_BRANCH}.${CI_PIPELINE_ID}
    - docker push $DOCKER_REGISTRY/${CI_PROJECT_NAME}:${CI_COMMIT_BRANCH}-latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always

deploy:
  stage: deploy
  script:
    - if [[ $CI_COMMIT_BRANCH == "master" ]]; then export ENVIRONMENT="prod" ; elif [[ $CI_COMMIT_BRANCH == "dev" ]]; then export ENVIRONMENT="dev"; else echo "BRANCH doesn't meet requirements" && exit 1; fi
    - cd helm/templates && sed -i "s/%ENVIRONMENT%/$ENVIRONMENT/g" * && sed -i "s/%IMAGETAG%/${CI_COMMIT_BRANCH}.${CI_PIPELINE_ID}/g" deployment.yaml && cd -
    - echo "Deploy is running for $ENVIRONMENT Environment"
    - helm template node-api-$ENVIRONMENT ./helm/
    - helm upgrade node-api-$ENVIRONMENT ./helm 
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always