apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.common.hpaName }}
  namespace : {{ .Values.%ENVIRONMENT%.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.common.appName }}
  minReplicas: {{ .Values.%ENVIRONMENT%.minReplicas }}
  maxReplicas: {{ .Values.%ENVIRONMENT%.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: {{ .Values.%ENVIRONMENT%.targetUtilizationType }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.%ENVIRONMENT%.targetUtilizationPercentage }}