apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-prod-data
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-prod-data