apiVersion: v1
kind: Service
metadata:
  name: postgres-prod
  Namespace: prod
  labels:
    app: postgres-prod
    role: service
spec:
  selector:
    app: postgres-prod
    role: service
  type: NodePort
  ports:
    - name: postgres-prod
      port: 5432
      targetPort: 5432
      protocol: TCP