apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-dev-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/postgres-dev
  storageClassName: standard