apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-dev-data
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-dev-data