apiVersion: v1
kind: Service
metadata:
  name: postgres-dev
  namespace: dev
  labels:
    app: postgres-dev
    role: service
spec:
  selector:
    app: postgres-dev
    role: service
  type: NodePort
  ports:
    - name: postgres-dev
      port: 5432
      targetPort: 5432
      protocol: TCP